### ISSUE TITLE
Contributing to docs website [DOCS] 

### ISSUE THREAD

**Issue by ngiangre** [COVID-19-electronic-health-system/PanFLUte#24]
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to consider/implement this update.

### Summary

To make a more robust documentation on the website, there should be a procedure to contribute to it. 

### Motivation

Better documentation increases accessibility etc. 

### Possible Alternatives

More work for those only "in the know".

**Comment by k105la** [comment]
Will be using Doxygen for documentation. 
Here is a quick link to Doxygen's Docs: https://www.doxygen.nl/manual/

**Comment by akilhylton** [comment]
closes #

**Comment by ngiangre** [comment]
cool documentation style!
